version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Ubuntu
build_script:
- sh: dotnet tool install paket --tool-path ./
- sh: ./fake.sh build -t Release
test: off
deploy: off
only_commits:
  message: /\[RELEASE\]/